---
apiVersion: v1
kind: ConfigMap

metadata:
  name: edpm-nodeset-values-post-ceph
  annotations:
    config.kubernetes.io/local-config: "true"

data:
  ceph:
    conf: _replaced_
    keyring: _replaced_

  nodeset:
    services:
      - install-certs
      - ceph-client
      - ovn
      - neutron-metadata
      - libvirt
      - nova-custom
