---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

components:
  - ../../../../lib/dataplane/nodeset

resources:
  - resources/nova-custom-config.yaml
  - resources/nova-custom-service.yaml

replacements:
  #
  # Nova
  #
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.nova-extra-config
    targets:
      - select:
          kind: ConfigMap
          name: nova-custom-config
        fieldPaths:
          - data.55-nova-extra\.conf
        options:
          create: true
