---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

components:
  - ../../../lib/nncp

replacements:

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.routes.config
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-0
        fieldPaths:
          - spec.desiredState.routes.config
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-1
        fieldPaths:
          - spec.desiredState.routes.config
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-1
        fieldPaths:
          - spec.desiredState.routes.config
