---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../../dt/uni04delta-ipv6/nncp
resources:
  - values.yaml
  - ocp_worker_nodes.yaml

replacements:
  # Static Node IPs: node-3
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_3.internalapi_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[name=internalapi].ipv6.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_3.tenant_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[name=tenant].ipv6.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_3.ctlplane_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[type=linux-bridge].ipv6.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_3.storage_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[name=storage].ipv6.address.0.ip

  # prefix-length: node-3
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ctlplane.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[type=linux-bridge].ipv6.address.0.prefix-length
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.internalapi.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[name=internalapi].ipv6.address.0.prefix-length
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.tenant.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[name=tenant].ipv6.address.0.prefix-length
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storage.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[name=storage].ipv6.address.0.prefix-length

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_3.name
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - metadata.name
          - spec.nodeSelector.[kubernetes.io/hostname]

patches:
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-0
    patch: |-
      - op: add
        path: /spec/nodeSelector/node-role.kubernetes.io~1master
        value: ""
      - op: remove
        path: /spec/nodeSelector/node-role.kubernetes.io~1worker
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-1
    patch: |-
      - op: add
        path: /spec/nodeSelector/node-role.kubernetes.io~1master
        value: ""
      - op: remove
        path: /spec/nodeSelector/node-role.kubernetes.io~1worker
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-2
    patch: |-
      - op: add
        path: /spec/nodeSelector/node-role.kubernetes.io~1master
        value: ""
      - op: remove
        path: /spec/nodeSelector/node-role.kubernetes.io~1worker
