---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-custom-config
data:
  25-nova-custom.conf: |
    [DEFAULT]
    # Override our defaults in this dt to get coverage for metadata-api based
    # cloud-init scenarios
    force_config_drive = False

---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: nova-custom
spec:
  label: dataplane-deployment-nova-custom
  dataSources:
    - configMapRef:
        name: nova-custom-config
    - secretRef:
        name: nova-cell1-compute-config
    - secretRef:
        name: nova-migration-ssh-key
  playbook: osp.edpm.nova
  caCerts: combined-ca-bundle
  edpmServiceType: nova
  containerImageFields:
    - NovaComputeImage
    - EdpmIscsidImage
