---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../dt/uni05epsilon/edpm-post-ceph/deployment

resources:
  - values.yaml

replacements:
  - source:
      kind: ConfigMap
      name: edpm-deployment-values-post-ceph
      fieldPath: data.servicesOverride
    targets:
      - select:
          kind: OpenStackDataPlaneDeployment
        fieldPaths:
          - spec.servicesOverride
        options:
          create: true
